import type { ProjectData } from '@/types/data/project';

/**
 * Snapshots of well-known repositories, used as the material for the public
 * cards on the landing page. Read from the GitHub API on 2 September 2026 and
 * committed, so the page renders without a network call. Contributors are
 * omitted: no template on the landing page draws them.
 */
const showcaseProjects = {
  linux: {
    repository: {
      name: 'linux',
      fullName: 'torvalds/linux',
      url: 'https://github.com/torvalds/linux',
      description: 'Linux kernel source tree',
      defaultBranch: 'master',
      createdAt: '2011-09-04T22:48:12Z',
      updatedAt: '2026-09-02T02:22:22Z',
      pushedAt: '2026-09-01T20:49:36Z',
      isFork: false,
      isArchived: false,
      license: { key: 'other', name: 'Other', spdxId: 'NOASSERTION' },
    },
    owner: {
      login: 'torvalds',
      avatarUrl: 'https://avatars.githubusercontent.com/u/1024025?v=4',
      url: 'https://github.com/torvalds',
      type: 'User',
    },
    metrics: {
      stars: 245_874,
      forks: 64_251,
      watchers: 8392,
      issues: 3,
      pullRequests: 0,
    },
    languages: [
      { name: 'C', bytes: 1_451_560_550, percentage: 97.8 },
      { name: 'Assembly', bytes: 9_614_338, percentage: 0.6 },
      { name: 'Rust', bytes: 6_578_923, percentage: 0.4 },
      { name: 'Shell', bytes: 6_286_806, percentage: 0.4 },
      { name: 'Python', bytes: 4_732_907, percentage: 0.3 },
      { name: 'Makefile', bytes: 3_001_394, percentage: 0.2 },
    ],
    topics: [],
    fetchedAt: '2026-09-02T02:30:00Z',
  },
  react: {
    repository: {
      name: 'react',
      fullName: 'react/react',
      url: 'https://github.com/react/react',
      description: 'The library for web and native user interfaces.',
      homepage: 'https://react.dev',
      defaultBranch: 'main',
      createdAt: '2013-05-24T16:15:54Z',
      updatedAt: '2026-09-02T02:23:44Z',
      pushedAt: '2026-09-01T22:14:29Z',
      isFork: false,
      isArchived: false,
      license: { key: 'mit', name: 'MIT License', spdxId: 'MIT' },
    },
    owner: {
      login: 'react',
      avatarUrl: 'https://avatars.githubusercontent.com/u/102812?v=4',
      url: 'https://github.com/react',
      type: 'Organization',
    },
    metrics: {
      stars: 248_646,
      forks: 51_267,
      watchers: 6602,
      issues: 852,
      pullRequests: 483,
    },
    languages: [
      { name: 'JavaScript', bytes: 5_687_506, percentage: 49.6 },
      { name: 'Rust', bytes: 2_973_061, percentage: 25.9 },
      { name: 'TypeScript', bytes: 2_567_778, percentage: 22.4 },
      { name: 'HTML', bytes: 116_629, percentage: 1.0 },
      { name: 'CSS', bytes: 95_930, percentage: 0.8 },
      { name: 'CoffeeScript', bytes: 18_691, percentage: 0.2 },
    ],
    topics: ['declarative', 'frontend', 'javascript', 'library', 'react', 'ui'],
    latestRelease: {
      tagName: 'v19.2.8',
      name: '19.2.8 (July 21st, 2026)',
      publishedAt: '2026-07-21T15:49:09Z',
      url: 'https://github.com/react/react/releases/tag/v19.2.8',
    },
    fetchedAt: '2026-09-02T02:30:00Z',
  },
  tailwind: {
    repository: {
      name: 'tailwindcss',
      fullName: 'tailwindlabs/tailwindcss',
      url: 'https://github.com/tailwindlabs/tailwindcss',
      description: 'A utility-first CSS framework for rapid UI development.',
      homepage: 'https://tailwindcss.com/',
      defaultBranch: 'main',
      createdAt: '2017-10-06T14:59:14Z',
      updatedAt: '2026-09-01T20:18:59Z',
      pushedAt: '2026-08-31T11:25:22Z',
      isFork: false,
      isArchived: false,
      license: { key: 'mit', name: 'MIT License', spdxId: 'MIT' },
    },
    owner: {
      login: 'tailwindlabs',
      avatarUrl: 'https://avatars.githubusercontent.com/u/67109815?v=4',
      url: 'https://github.com/tailwindlabs',
      type: 'Organization',
    },
    metrics: {
      stars: 97_420,
      forks: 5604,
      watchers: 763,
      issues: 30,
      pullRequests: 34,
    },
    languages: [
      { name: 'TypeScript', bytes: 3_830_093, percentage: 80.2 },
      { name: 'Rust', bytes: 853_122, percentage: 17.9 },
      { name: 'CSS', bytes: 29_112, percentage: 0.6 },
      { name: 'HTML', bytes: 28_296, percentage: 0.6 },
      { name: 'Haml', bytes: 17_585, percentage: 0.4 },
      { name: 'JavaScript', bytes: 15_508, percentage: 0.3 },
    ],
    topics: [
      'css',
      'css-framework',
      'functional-css',
      'postcss',
      'responsive',
      'tailwindcss',
    ],
    latestRelease: {
      tagName: 'v4.3.3',
      name: 'v4.3.3',
      publishedAt: '2026-07-16T11:55:08Z',
      url: 'https://github.com/tailwindlabs/tailwindcss/releases/tag/v4.3.3',
    },
    fetchedAt: '2026-09-02T02:30:00Z',
  },
  vite: {
    repository: {
      name: 'vite',
      fullName: 'vitejs/vite',
      url: 'https://github.com/vitejs/vite',
      description: "Next generation frontend tooling. It's fast!",
      homepage: 'http://vite.dev',
      defaultBranch: 'main',
      createdAt: '2020-04-21T05:03:57Z',
      updatedAt: '2026-09-02T00:28:40Z',
      pushedAt: '2026-09-01T08:39:44Z',
      isFork: false,
      isArchived: false,
      license: { key: 'mit', name: 'MIT License', spdxId: 'MIT' },
    },
    owner: {
      login: 'vitejs',
      avatarUrl: 'https://avatars.githubusercontent.com/u/65625612?v=4',
      url: 'https://github.com/vitejs',
      type: 'Organization',
    },
    metrics: {
      stars: 82_646,
      forks: 8691,
      watchers: 561,
      issues: 503,
      pullRequests: 266,
    },
    languages: [
      { name: 'TypeScript', bytes: 2_702_836, percentage: 83.2 },
      { name: 'JavaScript', bytes: 301_243, percentage: 9.3 },
      { name: 'HTML', bytes: 142_652, percentage: 4.4 },
      { name: 'CSS', bytes: 82_458, percentage: 2.5 },
      { name: 'Vue', bytes: 6450, percentage: 0.2 },
      { name: 'Svelte', bytes: 5659, percentage: 0.2 },
    ],
    topics: ['build-tool', 'dev-server', 'frontend', 'hmr', 'vite'],
    latestRelease: {
      tagName: 'create-vite@9.2.0',
      name: 'create-vite@9.2.0',
      publishedAt: '2026-08-24T04:58:55Z',
      url: 'https://github.com/vitejs/vite/releases/tag/create-vite%409.2.0',
    },
    fetchedAt: '2026-09-02T02:30:00Z',
  },
  shadcn: {
    repository: {
      name: 'ui',
      fullName: 'shadcn-ui/ui',
      url: 'https://github.com/shadcn-ui/ui',
      description:
        'A set of beautifully-designed, accessible components and a code distribution platform. Works with your favorite frameworks. Open Source. Open Code.',
      homepage: 'https://ui.shadcn.com',
      defaultBranch: 'main',
      createdAt: '2023-01-04T12:43:27Z',
      updatedAt: '2026-09-02T02:09:10Z',
      pushedAt: '2026-09-01T19:50:21Z',
      isFork: false,
      isArchived: false,
      license: { key: 'mit', name: 'MIT License', spdxId: 'MIT' },
    },
    owner: {
      login: 'shadcn-ui',
      avatarUrl: 'https://avatars.githubusercontent.com/u/139895814?v=4',
      url: 'https://github.com/shadcn-ui',
      type: 'Organization',
    },
    metrics: {
      stars: 122_738,
      forks: 10_065,
      watchers: 429,
      issues: 884,
      pullRequests: 1172,
    },
    languages: [
      { name: 'TypeScript', bytes: 16_713_062, percentage: 87.2 },
      { name: 'MDX', bytes: 1_727_462, percentage: 9.0 },
      { name: 'CSS', bytes: 704_834, percentage: 3.7 },
      { name: 'JavaScript', bytes: 17_099, percentage: 0.1 },
      { name: 'Astro', bytes: 1873, percentage: 0.0 },
      { name: 'Dockerfile', bytes: 1199, percentage: 0.0 },
    ],
    topics: ['base-ui', 'components', 'laravel', 'nextjs', 'radix-ui', 'react'],
    latestRelease: {
      tagName: 'shadcn@4.19.1',
      name: 'shadcn@4.19.1',
      publishedAt: '2026-08-31T09:55:48Z',
      url: 'https://github.com/shadcn-ui/ui/releases/tag/shadcn%404.19.1',
    },
    fetchedAt: '2026-09-02T02:30:00Z',
  },
  next: {
    repository: {
      name: 'next.js',
      fullName: 'vercel/next.js',
      url: 'https://github.com/vercel/next.js',
      description: 'The React Framework',
      homepage: 'https://nextjs.org',
      defaultBranch: 'canary',
      createdAt: '2016-10-05T23:32:51Z',
      updatedAt: '2026-09-02T02:12:54Z',
      pushedAt: '2026-09-02T02:20:10Z',
      isFork: false,
      isArchived: false,
      license: { key: 'mit', name: 'MIT License', spdxId: 'MIT' },
    },
    owner: {
      login: 'vercel',
      avatarUrl: 'https://avatars.githubusercontent.com/u/14985020?v=4',
      url: 'https://github.com/vercel',
      type: 'Organization',
    },
    metrics: {
      stars: 142_068,
      forks: 31_855,
      watchers: 1649,
      issues: 1208,
      pullRequests: 2249,
    },
    languages: [
      { name: 'JavaScript', bytes: 39_196_859, percentage: 51.0 },
      { name: 'TypeScript', bytes: 25_280_701, percentage: 32.9 },
      { name: 'Rust', bytes: 11_061_238, percentage: 14.4 },
      { name: 'MDX', bytes: 605_261, percentage: 0.8 },
      { name: 'CSS', bytes: 577_159, percentage: 0.8 },
      { name: 'Shell', bytes: 35_945, percentage: 0.0 },
    ],
    topics: ['blog', 'browser', 'compiler', 'components', 'hybrid', 'nextjs'],
    latestRelease: {
      tagName: 'v16.3.4',
      name: 'v16.3.4',
      publishedAt: '2026-08-31T20:02:15Z',
      url: 'https://github.com/vercel/next.js/releases/tag/v16.3.4',
    },
    fetchedAt: '2026-09-02T02:30:00Z',
  },
} satisfies Record<string, ProjectData>;

export { showcaseProjects };
